apiVersion: v1
kind: Service
metadata:
  name: predictor-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: plaintext
    targetPort: 8000
  # Kubernetes-метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app: predictor