apiVersion: v1
kind: Service
metadata:
  name: project-service
  labels:
    app: project
spec:
  selector:
    app: project
  type: LoadBalancer
  ports:
    - port: 80
      name: project
      targetPort: 8000
  # Kubernetes-метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  