name: mlops CI

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: testing
      run: |
        pip install -r requirements/requirements-hw8.txt pytest httpx -e .
        pytest ./tests

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build --tag unclealfer/mlops-hw8 .

    - name: Push the Docker image
      run: |
        docker push unclealfer/mlops-hw8:latest
